// Generated by CoffeeScript 1.9.0
(function() {
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  window.Hand = (function(_super) {
    __extends(Hand, _super);

    function Hand() {
      return Hand.__super__.constructor.apply(this, arguments);
    }

    Hand.prototype.model = Card;

    Hand.prototype.initialize = function(array, _at_deck, _at_isDealer) {
      this.deck = _at_deck;
      this.isDealer = _at_isDealer;
      if (this.optimalScore() === 21 || this.minScore() >= 21) {
        return this.trigger('endOfGame', this);
      }
    };

    Hand.prototype.hit = function() {
      this.add(this.deck.pop());
      if (this.optimalScore() === 21 || this.minScore() >= 21) {
        return this.trigger('endOfGame', this);
      }
    };

    Hand.prototype.hasAce = function() {
      return this.reduce(function(memo, card) {
        return memo || card.get('value') === 1;
      }, 0);
    };

    Hand.prototype.minScore = function() {
      return this.reduce(function(score, card) {
        return score + (card.get('revealed') ? card.get('value') : 0);
      }, 0);
    };

    Hand.prototype.scores = function() {
      return [this.minScore(), this.minScore() + 10 * this.hasAce()];
    };

    Hand.prototype.optimalScore = function() {
      if (!this.hasAce()) {
        return this.scores()[0];
      } else if (this.scores()[1] <= 21) {
        return this.scores()[1];
      } else {
        return this.scores()[0];
      }
    };

    Hand.prototype.stand = function() {
      return this.trigger('endOfTurn', this);
    };

    return Hand;

  })(Backbone.Collection);

}).call(this);

//# sourceMappingURL=Hand.js.map
